<?php

namespace app\models;

use common\models\MessageEvent;
use Yii;

/**
 * This is the model class for table "message".
 *
 * @property int $id
 * @property string $name
 * @property int $tel
 * @property string $message
 * @property string $ip
 * @property int $status
 * @property string $curr_date
 */
class MessageModel extends \yii\db\ActiveRecord
{
    const EVENT_MESSAGE_SAVE='event_message_save';


    public function init()
    {
        $this->on(self::EVENT_MESSAGE_SAVE,[\Yii::$app->emailService, 'sendNotifyAdmin', ]);
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'message';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['tel', 'name','ip'], 'required'],
            [['tel', 'status'], 'integer'],
            [['curr_date'], 'safe'],
            [['message', 'name'], 'string', 'max' => 255],
            [['ip'], 'ip'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name'=>'имя',
            'tel' => 'телефон',
            'message' => 'сообщение',
            'ip' => 'Ip',
            'status' => 'Status',
            'curr_date' => 'Curr Date',
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        $event = new MessageEvent();
        $event->subject = "ВНИМАНИЕ! Запрос обратного звонка через сайт!";
        $event->htmlMessage = 'На сайт <b>ASTRA22.ru</b> поступил запрос звонка. <br> 
                                Необходимо его обработать в кратчайшие сроки!!!! По факту отзвона пациенту - информацию о факте обратного звонка передать Круглик Марине!<br>
                                <b>ИМЯ:</b>'.$this->name.' <br>
                                <b>ТЕЛЕФОН:</b>'.$this->tel.' <br>
                                <b>СООБЩЕНИЕ:</b>'.$this->message.' <br>
                                ';
        $this->trigger(SELF::EVENT_MESSAGE_SAVE, $event);
    }
}
